---
- hosts: all
  become: true
  vars_files:
    - ./vars/vars.yml
  tasks:
    - name: create environment file
      copy:
        dest: "bootcamp-app/.env"
        content: |
            # Host configuration
            PORT={{PORT}}
            HOST={{HOST}}
            NODE_ENV={{NODE_ENV}}
            HOST_URL={{HOST_URL}}
            COOKIE_ENCRYPT_PWD={{COOKIE_ENCRYPT_PWD}}

            # Okta configuration
            OKTA_ORG_URL={{OKTA_ORG_URL}}
            OKTA_CLIENT_ID={{OKTA_CLIENT_ID}}
            OKTA_CLIENT_SECRET={{OKTA_CLIENT_SECRET}}

            # Postgres configuration
            PGHOST={{PGHOST}}
            PGUSERNAME={{PGUSERNAME}}
            PGDATABASE={{PGDATABASE}}
            PGPASSWORD={{PGPASSWORD}}
            PGPORT={{PGPORT}}
