---
- hosts: all
  become: true
  vars_files:
    - ./vars/prod.yml
  tasks:

    - name: Install dependencies
      become: yes
      command: "npm install"
      args:
        chdir: /home/{{ vm_username }}/bootcamp-app

    - name: initiate the database
      command: 'npm run initdb'
      args:
        chdir: /home/{{ vm_username }}/bootcamp-app

    - name: Install PM2
      npm:
       name: pm2
       global: yes

    - name: Run pm2
      command: "sudo pm2 start 'npm run dev' && sudo pm2 save && sudo pm2 startup ubuntu"
      args:
        chdir: /home/{{ vm_username }}/bootcamp-app

    - name: reboot
      command: 'reboot now'
